image:
  - Ubuntu
  - Visual Studio 2017
version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
configuration: Release
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

branches:
  except:
    - ci/travis
    - /^dependabot\/.*/

matrix:
  fast_finish: true

build: off
test: off
deploy: off

install:
- sh: sudo apt-get update && sudo apt-get install -y libgit2-dev

build_script:
  - ps: .\build.ps1 --target=CI --configuration=$env:CONFIGURATION
  - sh: ./build.sh --target=CI --configuration=$CONFIGURATION


cache:
  - 'tools -> build.cake'
  - 'src/Cake.Warp/warp -> recipe.cake'
  - '.dotnet -> build.cake'

for:

-
  matrix:
    only:
      - image: Ubuntu
  environment:
    GITHUB_PASSWORD:
    MYGET_API_KEY:
    GITTER_TOKEN:
    SLACK_TOKEN:
    TWITTER_CONSUMER_KEY:
    TWITTER_ACCESS_TOKEN:
    NUGET_API_KEY:
    WYAM_ACCESS_TOKEN:
