pull_request_rules:
  - name: Add Documentation label for documentation changes, but not in source
    conditions:
      - "files~=^(docs/.*|README.md|CODE_OF_CONDUCT.md|CONTRIBUTING.md)$"
      - "-files~=*src/Cake.Warp/.*$"
    actions:
      label:
        add: ["Documentation"]
  - name: Add build label when no change in source, and not in documentation
    conditions:
      - "-files~=^(docs/.*|README.md|CODE_OF_CONDUCT.md|CONTRIBUTING.md)$"
      - "-files~=*src/Cake.Warp/.*$"
    actions:
      label:
        add: ["Build"]
  - name: "Add Breaking change when Cake.Core is mentioned in title"
    conditions:
      - "title~=Cake.Core"
    actions:
      label:
        add: ["Breaking Change"]
        remove: ["Build"] # In case dependabot was the one that opened this
  # Although we can not have mergify auto-merge PR's (because we require GPG signature)
  # We still want this rule, in case mergify suddenly signs commits.
  - name: "Merge Pull Request when CI passes, and no outstanding issues"
    conditions:
      - "status-success=continuous-integration/appveyor/pr"
      - "status-success=continuous-integration/travis-ci"
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
    actions:
      comment:
        message: "Thank you for your contribution, this PR will be merged by a human collaborator soon!"
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
